name: dna_ventures
version: 1.0.0+1
publish_to: none
description: A Flutter task project for company named DNA Ventures.
environment: 
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  bot_toast: ^4.0.1
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  get: 4.1.4
  get_storage: ^2.0.3
  image_picker: ^0.8.3
  intl: ^0.17.0
  flutter_switch: ^0.3.2
  path_provider: ^2.0.4
  sqflite: ^2.0.0+4

dev_dependencies: 
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/


